// DO NOT EDIT THIS FILE — it is a one-shot script run manually to regenerate example SVGs.
import { avatar } from '../packages/svg/src/index';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const styles = ['bloom', 'grain', 'brutalist', 'terminal', 'pixel', 'ghosts', 'bots', 'faces'] as const;

const names = [
	'Alice Wonder',
	'Ben Dover',
	'Cal Zorn',
	'Dee Light',
	'Evan Gelist',
	'Fay Kwest',
	'Gus Tavo',
	'Hue Mann',
	'Ivy League',
	'Jay Walker',
];

for (const style of styles) {
	for (let i = 0; i < 10; i++) {
		const name = names[i];
		const svg = avatar(name, { style, size: 256 });
		const filename = `example-${style}-${String(i + 1).padStart(2, '0')}.svg`;
		writeFileSync(join('docs', filename), svg);
		console.log(`Created ${filename} (${name})`);
	}
}
